app:
  active-models:
    datasource:
      url: jdbc:h2:mem:active-models;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          hbm2ddl:
            auto: none
          show_sql: false
  passive-models:
    datasource:
      url: jdbc:h2:mem:passive-models;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          hbm2ddl:
            auto: none
          show_sql: false